export const ROOT_CHANGED = 'ROOT_CHANGED'
export const NURSERIES_FETCHED = 'NURSERIES_FETCHED'
export const NURSERIES_SET_CURRENT = 'NURSERIES_SET_CURRENT'

export const SAMPLES_FETCHED = 'SAMPLES_FETCHED'

export const PARAMS_FETCHED = 'PARAMS_FETCHED'

export const USER_LOGEDIN = 'USER_LOGEDIN'
export const USER_LOGEDOUT = 'USER_LOGEDOUT'

export const PERMISSIONS_FETCHED = 'PERMISSIONS_FETCHED'

export const GET_CONFIG = 'GET_CONFIG'
export const SET_CONFIG = 'SET_CONFIG'